
/* File generated by gen_cfile.py. Should not be modified. */

#include "master_node.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 cDeviceModle = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS16 cHardwareVersion = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS16 cFirmwareVersion = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS16 cNode_ID = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS16 cMOS_ProtectTemp = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS16 cMotorProtectTemp = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS16 cUnderVoltage = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS16 cOverVoltage = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS16 cDissipationOn = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS16 cDissipationOff = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS16 cOverCurrent = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
UNS16 cReductionRatio = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
UNS16 cMaxSpeed = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
UNS16 cMaxPosition = 0x0;		/* Mapped at index 0x200D, subindex 0x00 */
UNS16 cMaxCurrent = 0x0;		/* Mapped at index 0x200E, subindex 0x00 */
UNS16 cIdLoopKp = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
UNS16 cIdLoopKi = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS16 cIdLoopKd = 0x0;		/* Mapped at index 0x2011, subindex 0x00 */
UNS16 cIdLoopKaw = 0x0;		/* Mapped at index 0x2012, subindex 0x00 */
UNS16 cIdLoopLimit = 0x0;		/* Mapped at index 0x2013, subindex 0x00 */
UNS16 cIqLoopKp = 0x0;		/* Mapped at index 0x2014, subindex 0x00 */
UNS16 cIqLoopKi = 0x0;		/* Mapped at index 0x2015, subindex 0x00 */
UNS16 cIqLoopKd = 0x0;		/* Mapped at index 0x2016, subindex 0x00 */
UNS16 cIqLoopKaw = 0x0;		/* Mapped at index 0x2017, subindex 0x00 */
UNS16 cIqLoopLimit = 0x0;		/* Mapped at index 0x2018, subindex 0x00 */
UNS16 cSpeedLoopKp = 0x0;		/* Mapped at index 0x2019, subindex 0x00 */
UNS16 cSpeedLoopKi = 0x0;		/* Mapped at index 0x201A, subindex 0x00 */
UNS16 cSpeedLoopKd = 0x0;		/* Mapped at index 0x201B, subindex 0x00 */
UNS16 cSpeedLoopKaw = 0x0;		/* Mapped at index 0x201C, subindex 0x00 */
UNS16 cSpeedLoopLimit = 0x0;		/* Mapped at index 0x201D, subindex 0x00 */
UNS16 cPositionLoopKp = 0x0;		/* Mapped at index 0x201E, subindex 0x00 */
UNS16 cPositionLoopKi = 0x0;		/* Mapped at index 0x201F, subindex 0x00 */
UNS16 cPositionLoopKd = 0x0;		/* Mapped at index 0x2020, subindex 0x00 */
UNS16 cPositionLoopKaw = 0x0;		/* Mapped at index 0x2021, subindex 0x00 */
UNS16 cPositionLoopLimit = 0x0;		/* Mapped at index 0x2022, subindex 0x00 */
UNS16 cErrorHistory[] =		/* Mapped at index 0x2023, subindex 0x01 - 0x0A */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 cActualPosition = 0x0;		/* Mapped at index 0x2024, subindex 0x00 */
UNS16 cActualSpeed = 0x0;		/* Mapped at index 0x2025, subindex 0x00 */
UNS16 cActualCurrent = 0x0;		/* Mapped at index 0x2026, subindex 0x00 */
UNS16 cActualMotorTemp = 0x0;		/* Mapped at index 0x2027, subindex 0x00 */
UNS16 cActualMosTemp = 0x0;		/* Mapped at index 0x2028, subindex 0x00 */
UNS16 cActualBusVoltage = 0x0;		/* Mapped at index 0x2029, subindex 0x00 */
UNS16 cMotorStatus = 0x0;		/* Mapped at index 0x202A, subindex 0x00 */
UNS16 cMotorOperation = 0x0;		/* Mapped at index 0x202B, subindex 0x00 */
INTEGER32 cReferencePosition = 0x0;		/* Mapped at index 0x202C, subindex 0x00 */
UNS16 cReferenceSpeed = 0x0;		/* Mapped at index 0x202D, subindex 0x00 */
UNS16 cReferenceCurrent = 0x0;		/* Mapped at index 0x202E, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 master_node_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 master_node_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 master_node_iam_a_slave = 0;

TIMER_HANDLE master_node_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 master_node_obj1000 = 0x0;	/* 0 */
                    subindex master_node_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&master_node_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 master_node_obj1001 = 0x0;	/* 0 */
                    subindex master_node_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_node_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 master_node_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 master_node_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex master_node_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_node_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 master_node_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 master_node_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 master_node_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 master_node_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 master_node_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 master_node_highestSubIndex_obj1016 = 0;
                    UNS32 master_node_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 master_node_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 master_node_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 master_node_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 master_node_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 master_node_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 master_node_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex master_node_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_node_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_node_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_node_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_node_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 master_node_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 master_node_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 master_node_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex master_node_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_node_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_node_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 master_node_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 master_node_obj1400_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 master_node_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_node_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_node_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_node_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_node_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_node_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_node_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_node_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 master_node_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 master_node_obj1401_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 master_node_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_node_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_node_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_node_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_node_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_node_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_node_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_node_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 master_node_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 master_node_obj1600[] = 
                    {
                      0x202A0010,	/* 539623440 */
                      0x20250010,	/* 539295760 */
                      0x20240010,	/* 539230224 */
                      0x20260010	/* 539361296 */
                    };
                    subindex master_node_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1600[3], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 master_node_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 master_node_obj1601[] = 
                    {
                      0x20270010,	/* 539426832 */
                      0x20290010	/* 539557904 */
                    };
                    subindex master_node_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1601[1], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 master_node_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 master_node_obj1800_COB_ID_used_by_PDO = 0x201;	/* 512 */
                    UNS8 master_node_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_node_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_node_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_node_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_node_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_node_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_node_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_node_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 master_node_highestSubIndex_obj1A00 = 3; /* number of subindex - 1*/
                    UNS32 master_node_obj1A00[] = 
                    {
                      0x202B0010,	/* 539688976 */
                      0x202D0010,	/* 539820048 */
                      0x202C0020	/* 539754528 */
                    };
                    subindex master_node_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_node_obj1A00[2], NULL }
                     };

/* index 0x2000 :   Mapped variable cDeviceModle */
                    subindex master_node_Index2000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cDeviceModle, NULL }
                     };

/* index 0x2001 :   Mapped variable cHardwareVersion */
                    subindex master_node_Index2001[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cHardwareVersion, NULL }
                     };

/* index 0x2002 :   Mapped variable cFirmwareVersion */
                    subindex master_node_Index2002[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cFirmwareVersion, NULL }
                     };

/* index 0x2003 :   Mapped variable cNode_ID */
                    subindex master_node_Index2003[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cNode_ID, NULL }
                     };

/* index 0x2004 :   Mapped variable cMOS_ProtectTemp */
                    subindex master_node_Index2004[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cMOS_ProtectTemp, NULL }
                     };

/* index 0x2005 :   Mapped variable cMotorProtectTemp */
                    subindex master_node_Index2005[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cMotorProtectTemp, NULL }
                     };

/* index 0x2006 :   Mapped variable cUnderVoltage */
                    subindex master_node_Index2006[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cUnderVoltage, NULL }
                     };

/* index 0x2007 :   Mapped variable cOverVoltage */
                    subindex master_node_Index2007[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cOverVoltage, NULL }
                     };

/* index 0x2008 :   Mapped variable cDissipationOn */
                    subindex master_node_Index2008[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cDissipationOn, NULL }
                     };

/* index 0x2009 :   Mapped variable cDissipationOff */
                    subindex master_node_Index2009[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cDissipationOff, NULL }
                     };

/* index 0x200A :   Mapped variable cOverCurrent */
                    subindex master_node_Index200A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cOverCurrent, NULL }
                     };

/* index 0x200B :   Mapped variable cReductionRatio */
                    subindex master_node_Index200B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cReductionRatio, NULL }
                     };

/* index 0x200C :   Mapped variable cMaxSpeed */
                    subindex master_node_Index200C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cMaxSpeed, NULL }
                     };

/* index 0x200D :   Mapped variable cMaxPosition */
                    subindex master_node_Index200D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cMaxPosition, NULL }
                     };

/* index 0x200E :   Mapped variable cMaxCurrent */
                    subindex master_node_Index200E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cMaxCurrent, NULL }
                     };

/* index 0x200F :   Mapped variable cIdLoopKp */
                    subindex master_node_Index200F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIdLoopKp, NULL }
                     };

/* index 0x2010 :   Mapped variable cIdLoopKi */
                    subindex master_node_Index2010[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIdLoopKi, NULL }
                     };

/* index 0x2011 :   Mapped variable cIdLoopKd */
                    subindex master_node_Index2011[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIdLoopKd, NULL }
                     };

/* index 0x2012 :   Mapped variable cIdLoopKaw */
                    subindex master_node_Index2012[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIdLoopKaw, NULL }
                     };

/* index 0x2013 :   Mapped variable cIdLoopLimit */
                    subindex master_node_Index2013[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIdLoopLimit, NULL }
                     };

/* index 0x2014 :   Mapped variable cIqLoopKp */
                    subindex master_node_Index2014[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIqLoopKp, NULL }
                     };

/* index 0x2015 :   Mapped variable cIqLoopKi */
                    subindex master_node_Index2015[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIqLoopKi, NULL }
                     };

/* index 0x2016 :   Mapped variable cIqLoopKd */
                    subindex master_node_Index2016[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIqLoopKd, NULL }
                     };

/* index 0x2017 :   Mapped variable cIqLoopKaw */
                    subindex master_node_Index2017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIqLoopKaw, NULL }
                     };

/* index 0x2018 :   Mapped variable cIqLoopLimit */
                    subindex master_node_Index2018[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cIqLoopLimit, NULL }
                     };

/* index 0x2019 :   Mapped variable cSpeedLoopKp */
                    subindex master_node_Index2019[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cSpeedLoopKp, NULL }
                     };

/* index 0x201A :   Mapped variable cSpeedLoopKi */
                    subindex master_node_Index201A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cSpeedLoopKi, NULL }
                     };

/* index 0x201B :   Mapped variable cSpeedLoopKd */
                    subindex master_node_Index201B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cSpeedLoopKd, NULL }
                     };

/* index 0x201C :   Mapped variable cSpeedLoopKaw */
                    subindex master_node_Index201C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cSpeedLoopKaw, NULL }
                     };

/* index 0x201D :   Mapped variable cSpeedLoopLimit */
                    subindex master_node_Index201D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cSpeedLoopLimit, NULL }
                     };

/* index 0x201E :   Mapped variable cPositionLoopKp */
                    subindex master_node_Index201E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cPositionLoopKp, NULL }
                     };

/* index 0x201F :   Mapped variable cPositionLoopKi */
                    subindex master_node_Index201F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cPositionLoopKi, NULL }
                     };

/* index 0x2020 :   Mapped variable cPositionLoopKd */
                    subindex master_node_Index2020[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cPositionLoopKd, NULL }
                     };

/* index 0x2021 :   Mapped variable cPositionLoopKaw */
                    subindex master_node_Index2021[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cPositionLoopKaw, NULL }
                     };

/* index 0x2022 :   Mapped variable cPositionLoopLimit */
                    subindex master_node_Index2022[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cPositionLoopLimit, NULL }
                     };

/* index 0x2023 :   Mapped variable cErrorHistory */
                    UNS8 master_node_highestSubIndex_obj2023 = 10; /* number of subindex - 1*/
                    subindex master_node_Index2023[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_node_highestSubIndex_obj2023, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[0], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[1], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[2], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[3], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[4], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[5], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[6], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[7], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[8], NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&cErrorHistory[9], NULL }
                     };

/* index 0x2024 :   Mapped variable cActualPosition */
                    subindex master_node_Index2024[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cActualPosition, NULL }
                     };

/* index 0x2025 :   Mapped variable cActualSpeed */
                    subindex master_node_Index2025[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cActualSpeed, NULL }
                     };

/* index 0x2026 :   Mapped variable cActualCurrent */
                    subindex master_node_Index2026[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cActualCurrent, NULL }
                     };

/* index 0x2027 :   Mapped variable cActualMotorTemp */
                    subindex master_node_Index2027[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cActualMotorTemp, NULL }
                     };

/* index 0x2028 :   Mapped variable cActualMosTemp */
                    subindex master_node_Index2028[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cActualMosTemp, NULL }
                     };

/* index 0x2029 :   Mapped variable cActualBusVoltage */
                    subindex master_node_Index2029[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cActualBusVoltage, NULL }
                     };

/* index 0x202A :   Mapped variable cMotorStatus */
                    subindex master_node_Index202A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cMotorStatus, NULL }
                     };

/* index 0x202B :   Mapped variable cMotorOperation */
                    subindex master_node_Index202B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cMotorOperation, NULL }
                     };

/* index 0x202C :   Mapped variable cReferencePosition */
                    subindex master_node_Index202C[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&cReferencePosition, NULL }
                     };

/* index 0x202D :   Mapped variable cReferenceSpeed */
                    subindex master_node_Index202D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cReferenceSpeed, NULL }
                     };

/* index 0x202E :   Mapped variable cReferenceCurrent */
                    subindex master_node_Index202E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&cReferenceCurrent, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable master_node_objdict[] = 
{
  { (subindex*)master_node_Index1000,sizeof(master_node_Index1000)/sizeof(master_node_Index1000[0]), 0x1000},
  { (subindex*)master_node_Index1001,sizeof(master_node_Index1001)/sizeof(master_node_Index1001[0]), 0x1001},
  { (subindex*)master_node_Index1018,sizeof(master_node_Index1018)/sizeof(master_node_Index1018[0]), 0x1018},
  { (subindex*)master_node_Index1200,sizeof(master_node_Index1200)/sizeof(master_node_Index1200[0]), 0x1200},
  { (subindex*)master_node_Index1400,sizeof(master_node_Index1400)/sizeof(master_node_Index1400[0]), 0x1400},
  { (subindex*)master_node_Index1401,sizeof(master_node_Index1401)/sizeof(master_node_Index1401[0]), 0x1401},
  { (subindex*)master_node_Index1600,sizeof(master_node_Index1600)/sizeof(master_node_Index1600[0]), 0x1600},
  { (subindex*)master_node_Index1601,sizeof(master_node_Index1601)/sizeof(master_node_Index1601[0]), 0x1601},
  { (subindex*)master_node_Index1800,sizeof(master_node_Index1800)/sizeof(master_node_Index1800[0]), 0x1800},
  { (subindex*)master_node_Index1A00,sizeof(master_node_Index1A00)/sizeof(master_node_Index1A00[0]), 0x1A00},
  { (subindex*)master_node_Index2000,sizeof(master_node_Index2000)/sizeof(master_node_Index2000[0]), 0x2000},
  { (subindex*)master_node_Index2001,sizeof(master_node_Index2001)/sizeof(master_node_Index2001[0]), 0x2001},
  { (subindex*)master_node_Index2002,sizeof(master_node_Index2002)/sizeof(master_node_Index2002[0]), 0x2002},
  { (subindex*)master_node_Index2003,sizeof(master_node_Index2003)/sizeof(master_node_Index2003[0]), 0x2003},
  { (subindex*)master_node_Index2004,sizeof(master_node_Index2004)/sizeof(master_node_Index2004[0]), 0x2004},
  { (subindex*)master_node_Index2005,sizeof(master_node_Index2005)/sizeof(master_node_Index2005[0]), 0x2005},
  { (subindex*)master_node_Index2006,sizeof(master_node_Index2006)/sizeof(master_node_Index2006[0]), 0x2006},
  { (subindex*)master_node_Index2007,sizeof(master_node_Index2007)/sizeof(master_node_Index2007[0]), 0x2007},
  { (subindex*)master_node_Index2008,sizeof(master_node_Index2008)/sizeof(master_node_Index2008[0]), 0x2008},
  { (subindex*)master_node_Index2009,sizeof(master_node_Index2009)/sizeof(master_node_Index2009[0]), 0x2009},
  { (subindex*)master_node_Index200A,sizeof(master_node_Index200A)/sizeof(master_node_Index200A[0]), 0x200A},
  { (subindex*)master_node_Index200B,sizeof(master_node_Index200B)/sizeof(master_node_Index200B[0]), 0x200B},
  { (subindex*)master_node_Index200C,sizeof(master_node_Index200C)/sizeof(master_node_Index200C[0]), 0x200C},
  { (subindex*)master_node_Index200D,sizeof(master_node_Index200D)/sizeof(master_node_Index200D[0]), 0x200D},
  { (subindex*)master_node_Index200E,sizeof(master_node_Index200E)/sizeof(master_node_Index200E[0]), 0x200E},
  { (subindex*)master_node_Index200F,sizeof(master_node_Index200F)/sizeof(master_node_Index200F[0]), 0x200F},
  { (subindex*)master_node_Index2010,sizeof(master_node_Index2010)/sizeof(master_node_Index2010[0]), 0x2010},
  { (subindex*)master_node_Index2011,sizeof(master_node_Index2011)/sizeof(master_node_Index2011[0]), 0x2011},
  { (subindex*)master_node_Index2012,sizeof(master_node_Index2012)/sizeof(master_node_Index2012[0]), 0x2012},
  { (subindex*)master_node_Index2013,sizeof(master_node_Index2013)/sizeof(master_node_Index2013[0]), 0x2013},
  { (subindex*)master_node_Index2014,sizeof(master_node_Index2014)/sizeof(master_node_Index2014[0]), 0x2014},
  { (subindex*)master_node_Index2015,sizeof(master_node_Index2015)/sizeof(master_node_Index2015[0]), 0x2015},
  { (subindex*)master_node_Index2016,sizeof(master_node_Index2016)/sizeof(master_node_Index2016[0]), 0x2016},
  { (subindex*)master_node_Index2017,sizeof(master_node_Index2017)/sizeof(master_node_Index2017[0]), 0x2017},
  { (subindex*)master_node_Index2018,sizeof(master_node_Index2018)/sizeof(master_node_Index2018[0]), 0x2018},
  { (subindex*)master_node_Index2019,sizeof(master_node_Index2019)/sizeof(master_node_Index2019[0]), 0x2019},
  { (subindex*)master_node_Index201A,sizeof(master_node_Index201A)/sizeof(master_node_Index201A[0]), 0x201A},
  { (subindex*)master_node_Index201B,sizeof(master_node_Index201B)/sizeof(master_node_Index201B[0]), 0x201B},
  { (subindex*)master_node_Index201C,sizeof(master_node_Index201C)/sizeof(master_node_Index201C[0]), 0x201C},
  { (subindex*)master_node_Index201D,sizeof(master_node_Index201D)/sizeof(master_node_Index201D[0]), 0x201D},
  { (subindex*)master_node_Index201E,sizeof(master_node_Index201E)/sizeof(master_node_Index201E[0]), 0x201E},
  { (subindex*)master_node_Index201F,sizeof(master_node_Index201F)/sizeof(master_node_Index201F[0]), 0x201F},
  { (subindex*)master_node_Index2020,sizeof(master_node_Index2020)/sizeof(master_node_Index2020[0]), 0x2020},
  { (subindex*)master_node_Index2021,sizeof(master_node_Index2021)/sizeof(master_node_Index2021[0]), 0x2021},
  { (subindex*)master_node_Index2022,sizeof(master_node_Index2022)/sizeof(master_node_Index2022[0]), 0x2022},
  { (subindex*)master_node_Index2023,sizeof(master_node_Index2023)/sizeof(master_node_Index2023[0]), 0x2023},
  { (subindex*)master_node_Index2024,sizeof(master_node_Index2024)/sizeof(master_node_Index2024[0]), 0x2024},
  { (subindex*)master_node_Index2025,sizeof(master_node_Index2025)/sizeof(master_node_Index2025[0]), 0x2025},
  { (subindex*)master_node_Index2026,sizeof(master_node_Index2026)/sizeof(master_node_Index2026[0]), 0x2026},
  { (subindex*)master_node_Index2027,sizeof(master_node_Index2027)/sizeof(master_node_Index2027[0]), 0x2027},
  { (subindex*)master_node_Index2028,sizeof(master_node_Index2028)/sizeof(master_node_Index2028[0]), 0x2028},
  { (subindex*)master_node_Index2029,sizeof(master_node_Index2029)/sizeof(master_node_Index2029[0]), 0x2029},
  { (subindex*)master_node_Index202A,sizeof(master_node_Index202A)/sizeof(master_node_Index202A[0]), 0x202A},
  { (subindex*)master_node_Index202B,sizeof(master_node_Index202B)/sizeof(master_node_Index202B[0]), 0x202B},
  { (subindex*)master_node_Index202C,sizeof(master_node_Index202C)/sizeof(master_node_Index202C[0]), 0x202C},
  { (subindex*)master_node_Index202D,sizeof(master_node_Index202D)/sizeof(master_node_Index202D[0]), 0x202D},
  { (subindex*)master_node_Index202E,sizeof(master_node_Index202E)/sizeof(master_node_Index202E[0]), 0x202E},
};

const indextable * master_node_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1018: i = 2;break;
		case 0x1200: i = 3;break;
		case 0x1400: i = 4;break;
		case 0x1401: i = 5;break;
		case 0x1600: i = 6;break;
		case 0x1601: i = 7;break;
		case 0x1800: i = 8;break;
		case 0x1A00: i = 9;break;
		case 0x2000: i = 10;break;
		case 0x2001: i = 11;break;
		case 0x2002: i = 12;break;
		case 0x2003: i = 13;break;
		case 0x2004: i = 14;break;
		case 0x2005: i = 15;break;
		case 0x2006: i = 16;break;
		case 0x2007: i = 17;break;
		case 0x2008: i = 18;break;
		case 0x2009: i = 19;break;
		case 0x200A: i = 20;break;
		case 0x200B: i = 21;break;
		case 0x200C: i = 22;break;
		case 0x200D: i = 23;break;
		case 0x200E: i = 24;break;
		case 0x200F: i = 25;break;
		case 0x2010: i = 26;break;
		case 0x2011: i = 27;break;
		case 0x2012: i = 28;break;
		case 0x2013: i = 29;break;
		case 0x2014: i = 30;break;
		case 0x2015: i = 31;break;
		case 0x2016: i = 32;break;
		case 0x2017: i = 33;break;
		case 0x2018: i = 34;break;
		case 0x2019: i = 35;break;
		case 0x201A: i = 36;break;
		case 0x201B: i = 37;break;
		case 0x201C: i = 38;break;
		case 0x201D: i = 39;break;
		case 0x201E: i = 40;break;
		case 0x201F: i = 41;break;
		case 0x2020: i = 42;break;
		case 0x2021: i = 43;break;
		case 0x2022: i = 44;break;
		case 0x2023: i = 45;break;
		case 0x2024: i = 46;break;
		case 0x2025: i = 47;break;
		case 0x2026: i = 48;break;
		case 0x2027: i = 49;break;
		case 0x2028: i = 50;break;
		case 0x2029: i = 51;break;
		case 0x202A: i = 52;break;
		case 0x202B: i = 53;break;
		case 0x202C: i = 54;break;
		case 0x202D: i = 55;break;
		case 0x202E: i = 56;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &master_node_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status master_node_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index master_node_firstIndex = {
  3, /* SDO_SVR */
  0, /* SDO_CLT */
  4, /* PDO_RCV */
  6, /* PDO_RCV_MAP */
  8, /* PDO_TRS */
  9 /* PDO_TRS_MAP */
};

const quick_index master_node_lastIndex = {
  3, /* SDO_SVR */
  0, /* SDO_CLT */
  5, /* PDO_RCV */
  7, /* PDO_RCV_MAP */
  8, /* PDO_TRS */
  9 /* PDO_TRS_MAP */
};

const UNS16 master_node_ObjdictSize = sizeof(master_node_objdict)/sizeof(master_node_objdict[0]); 

CO_Data master_node_Data = CANOPEN_NODE_DATA_INITIALIZER(master_node);

