
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_1_H
#define MASTER_1_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 master_1_valueRangeTest (UNS8 typeValue, void * value);
const indextable * master_1_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data master_1_Data;
extern UNS16 Mode;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS16 Speed_ref;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS16 Position_ref;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 Torque_ref;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 Status;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 Speed_actual;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS16 Position_actual;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS16 Torque_actual;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 V_bus;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 Temp;		/* Mapped at index 0x2009, subindex 0x00*/

#endif // MASTER(3_9)_H
