
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestSlave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 Mode = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS16 Speed_ref = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS16 Position_ref = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS16 Torque_ref = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS16 Status = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS16 Speed_actual = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS16 Position_actual = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS16 Torque_actual = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS16 V_bus = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS16 Temp = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 master_1_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 master_1_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 master_1_iam_a_slave = 0;

TIMER_HANDLE master_1_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 master_1_obj1000 = 0x0;	/* 0 */
                    subindex master_1_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&master_1_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 master_1_obj1001 = 0x0;	/* 0 */
                    subindex master_1_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_1_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 master_1_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 master_1_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex master_1_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&master_1_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_1_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 master_1_obj1005 = 0x80;	/* 128 */
                    subindex master_1_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 master_1_obj1006 = 0x1;	/* 1 */
                    subindex master_1_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 master_1_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 master_1_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 master_1_obj1014 = 0x80;	/* 128 */
                    subindex master_1_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1014, NULL }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 master_1_highestSubIndex_obj1016 = 0;
                    UNS32 master_1_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 master_1_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 master_1_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 master_1_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 master_1_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 master_1_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 master_1_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex master_1_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_1_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_1_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_1_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_1_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&master_1_obj1018_Serial_Number, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 master_1_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 master_1_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 master_1_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_1_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_1_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_1_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_1_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_1_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_1_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_1_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_1_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 master_1_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 master_1_obj1401_COB_ID_used_by_PDO = 0x281;	/* 641 */
                    UNS8 master_1_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_1_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_1_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_1_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_1_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_1_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_1_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_1_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_1_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 master_1_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 master_1_obj1600[] = 
                    {
                      0x20040010,	/* 537133072 */
                      0x20050010,	/* 537198608 */
                      0x20060010,	/* 537264144 */
                      0x20070010	/* 537329680 */
                    };
                    subindex master_1_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1600[3], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 master_1_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 master_1_obj1601[] = 
                    {
                      0x20090010,	/* 537460752 */
                      0x20080010	/* 537395216 */
                    };
                    subindex master_1_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1601[1], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 master_1_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 master_1_obj1800_COB_ID_used_by_PDO = 0x201;	/* 513 */
                    UNS8 master_1_obj1800_Transmission_Type = 0x1;	/* 1 */
                    UNS16 master_1_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_1_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_1_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 master_1_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex master_1_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_1_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_1_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&master_1_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 master_1_highestSubIndex_obj1A00 = 4; /* number of subindex - 1*/
                    UNS32 master_1_obj1A00[] = 
                    {
                      0x20000010,	/* 536870928 */
                      0x20010010,	/* 536936464 */
                      0x20020010,	/* 537002000 */
                      0x20030010	/* 537067536 */
                    };
                    subindex master_1_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_1_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&master_1_obj1A00[3], NULL }
                     };

/* index 0x2000 :   Mapped variable Mode */
                    subindex master_1_Index2000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Mode, NULL }
                     };

/* index 0x2001 :   Mapped variable Speed_ref */
                    subindex master_1_Index2001[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Speed_ref, NULL }
                     };

/* index 0x2002 :   Mapped variable Position_ref */
                    subindex master_1_Index2002[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Position_ref, NULL }
                     };

/* index 0x2003 :   Mapped variable Torque_ref */
                    subindex master_1_Index2003[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Torque_ref, NULL }
                     };

/* index 0x2004 :   Mapped variable Status */
                    subindex master_1_Index2004[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Status, NULL }
                     };

/* index 0x2005 :   Mapped variable Speed_actual */
                    subindex master_1_Index2005[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Speed_actual, NULL }
                     };

/* index 0x2006 :   Mapped variable Position_actual */
                    subindex master_1_Index2006[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Position_actual, NULL }
                     };

/* index 0x2007 :   Mapped variable Torque_actual */
                    subindex master_1_Index2007[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Torque_actual, NULL }
                     };

/* index 0x2008 :   Mapped variable V_bus */
                    subindex master_1_Index2008[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&V_bus, NULL }
                     };

/* index 0x2009 :   Mapped variable Temp */
                    subindex master_1_Index2009[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Temp, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable master_1_objdict[] = 
{
  { (subindex*)master_1_Index1000,sizeof(master_1_Index1000)/sizeof(master_1_Index1000[0]), 0x1000},
  { (subindex*)master_1_Index1001,sizeof(master_1_Index1001)/sizeof(master_1_Index1001[0]), 0x1001},
  { (subindex*)master_1_Index1005,sizeof(master_1_Index1005)/sizeof(master_1_Index1005[0]), 0x1005},
  { (subindex*)master_1_Index1006,sizeof(master_1_Index1006)/sizeof(master_1_Index1006[0]), 0x1006},
  { (subindex*)master_1_Index1014,sizeof(master_1_Index1014)/sizeof(master_1_Index1014[0]), 0x1014},
  { (subindex*)master_1_Index1018,sizeof(master_1_Index1018)/sizeof(master_1_Index1018[0]), 0x1018},
  { (subindex*)master_1_Index1400,sizeof(master_1_Index1400)/sizeof(master_1_Index1400[0]), 0x1400},
  { (subindex*)master_1_Index1401,sizeof(master_1_Index1401)/sizeof(master_1_Index1401[0]), 0x1401},
  { (subindex*)master_1_Index1600,sizeof(master_1_Index1600)/sizeof(master_1_Index1600[0]), 0x1600},
  { (subindex*)master_1_Index1601,sizeof(master_1_Index1601)/sizeof(master_1_Index1601[0]), 0x1601},
  { (subindex*)master_1_Index1800,sizeof(master_1_Index1800)/sizeof(master_1_Index1800[0]), 0x1800},
  { (subindex*)master_1_Index1A00,sizeof(master_1_Index1A00)/sizeof(master_1_Index1A00[0]), 0x1A00},
  { (subindex*)master_1_Index2000,sizeof(master_1_Index2000)/sizeof(master_1_Index2000[0]), 0x2000},
  { (subindex*)master_1_Index2001,sizeof(master_1_Index2001)/sizeof(master_1_Index2001[0]), 0x2001},
  { (subindex*)master_1_Index2002,sizeof(master_1_Index2002)/sizeof(master_1_Index2002[0]), 0x2002},
  { (subindex*)master_1_Index2003,sizeof(master_1_Index2003)/sizeof(master_1_Index2003[0]), 0x2003},
  { (subindex*)master_1_Index2004,sizeof(master_1_Index2004)/sizeof(master_1_Index2004[0]), 0x2004},
  { (subindex*)master_1_Index2005,sizeof(master_1_Index2005)/sizeof(master_1_Index2005[0]), 0x2005},
  { (subindex*)master_1_Index2006,sizeof(master_1_Index2006)/sizeof(master_1_Index2006[0]), 0x2006},
  { (subindex*)master_1_Index2007,sizeof(master_1_Index2007)/sizeof(master_1_Index2007[0]), 0x2007},
  { (subindex*)master_1_Index2008,sizeof(master_1_Index2008)/sizeof(master_1_Index2008[0]), 0x2008},
  { (subindex*)master_1_Index2009,sizeof(master_1_Index2009)/sizeof(master_1_Index2009[0]), 0x2009},
};

const indextable * master_1_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1014: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1401: i = 7;break;
		case 0x1600: i = 8;break;
		case 0x1601: i = 9;break;
		case 0x1800: i = 10;break;
		case 0x1A00: i = 11;break;
		case 0x2000: i = 12;break;
		case 0x2001: i = 13;break;
		case 0x2002: i = 14;break;
		case 0x2003: i = 15;break;
		case 0x2004: i = 16;break;
		case 0x2005: i = 17;break;
		case 0x2006: i = 18;break;
		case 0x2007: i = 19;break;
		case 0x2008: i = 20;break;
		case 0x2009: i = 21;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &master_1_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status master_1_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index master_1_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

const quick_index master_1_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

const UNS16 master_1_ObjdictSize = sizeof(master_1_objdict)/sizeof(master_1_objdict[0]); 

CO_Data master_1_Data = CANOPEN_NODE_DATA_INITIALIZER(master_1);

