
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SLAVE_NODE_H
#define SLAVE_NODE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 slave_node_valueRangeTest (UNS8 typeValue, void * value);
const indextable * slave_node_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data slave_node_Data;
extern UNS16 cDeviceModle;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS16 cHardwareVersion;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS16 cFirmwareVersion;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 cNode_ID;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 cMOS_ProtectTemp;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 cMotorProtectTemp;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS16 cUnderVoltage;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS16 cOverVoltage;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 cDissipationOn;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 cDissipationOff;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 cOverCurrent;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS16 cReductionRatio;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS16 cMaxSpeed;		/* Mapped at index 0x200C, subindex 0x00*/
extern UNS16 cMaxPosition;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS16 cMaxCurrent;		/* Mapped at index 0x200E, subindex 0x00*/
extern UNS16 cIdLoopKp;		/* Mapped at index 0x200F, subindex 0x00*/
extern UNS16 cIdLoopKi;		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS16 cIdLoopKd;		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS16 cIdLoopKaw;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS16 cIdLoopLimit;		/* Mapped at index 0x2013, subindex 0x00*/
extern UNS16 cIqLoopKp;		/* Mapped at index 0x2014, subindex 0x00*/
extern UNS16 cIqLoopKi;		/* Mapped at index 0x2015, subindex 0x00*/
extern UNS16 cIqLoopKd;		/* Mapped at index 0x2016, subindex 0x00*/
extern UNS16 cIqLoopKaw;		/* Mapped at index 0x2017, subindex 0x00*/
extern UNS16 cIqLoopLimit;		/* Mapped at index 0x2018, subindex 0x00*/
extern UNS16 cSpeedLoopKp;		/* Mapped at index 0x2019, subindex 0x00*/
extern UNS16 cSpeedLoopKi;		/* Mapped at index 0x201A, subindex 0x00*/
extern UNS16 cSpeedLoopKd;		/* Mapped at index 0x201B, subindex 0x00*/
extern UNS16 cSpeedLoopKaw;		/* Mapped at index 0x201C, subindex 0x00*/
extern UNS16 cSpeedLoopLimit;		/* Mapped at index 0x201D, subindex 0x00*/
extern UNS16 cPositionLoopKp;		/* Mapped at index 0x201E, subindex 0x00*/
extern UNS16 cPositionLoopKi;		/* Mapped at index 0x201F, subindex 0x00*/
extern UNS16 cPositionLoopKd;		/* Mapped at index 0x2020, subindex 0x00*/
extern UNS16 cPositionLoopKaw;		/* Mapped at index 0x2021, subindex 0x00*/
extern UNS16 cPositionLoopLimit;		/* Mapped at index 0x2022, subindex 0x00*/
extern UNS16 cErrorHistory[10];		/* Mapped at index 0x2023, subindex 0x01 - 0x0A */
extern UNS16 cActualPosition;		/* Mapped at index 0x2024, subindex 0x00*/
extern UNS16 cActualSpeed;		/* Mapped at index 0x2025, subindex 0x00*/
extern UNS16 cActualCurrent;		/* Mapped at index 0x2026, subindex 0x00*/
extern UNS16 cActualMotorTemp;		/* Mapped at index 0x2027, subindex 0x00*/
extern UNS16 cActualMosTemp;		/* Mapped at index 0x2028, subindex 0x00*/
extern UNS16 cActualBusVoltage;		/* Mapped at index 0x2029, subindex 0x00*/
extern UNS16 cMotorStatus;		/* Mapped at index 0x202A, subindex 0x00*/
extern UNS16 cMotorOperation;		/* Mapped at index 0x202B, subindex 0x00*/
extern UNS16 cReferencePosition;		/* Mapped at index 0x202C, subindex 0x00*/
extern UNS16 cReferenceSpeed;		/* Mapped at index 0x202D, subindex 0x00*/
extern UNS16 cReferenceCurrent;		/* Mapped at index 0x202E, subindex 0x00*/

#endif // SLAVE_NODE_H
